[general]
bpp = 4
transparent = "0x5D53"
output_type = "both"
destination = "./examples"

[[unit]]
name = "test"
metatile_width = 5
metatile_height = 5
palette = ""
palette_include = 1
generate_palette = 0


[[unit]]
name = "I_1"
metatile_width = 4
metatile_height = 4
palette = ""
palette_include = 0
generate_palette = 0


[[unit]]
name = "I_2"
metatile_width = 4
metatile_height = 4
palette = "./faulty_path"
palette_include = 0
generate_palette = 1


[[unit]]
name = "I_3"
metatile_width = 4
metatile_height = 4
palette = ""
palette_include = 0
generate_palette = 1
